desmos-labs/dpm

src/components/tx/MessageMultiSend.tsx
src/components/tx/TxMessage.tsx
src/components/tx/list/MessageMultiSendListItem.tsx
src/components/tx/list/TransactionListMessageItem.tsx
src/graphql/hooks/useFetchTxsGrouppedByDate.ts
src/i18n/en.json
src/types/encodeobject.ts
src/types/msgtypes.ts

This PR implements the visualization of the MsgMultiSend in the list of transactions and when visualizing the details of a transaction.
Closes: #28 
---
Transaction list:
Transaction details:

Implement MsgMultiSend visualization

---

src/lib/EncryptionUtils/index.ts

Closes: #XXXX
This PR bumps the pbkdf2 iterations to 100,100 and use the first instal time in ms as salt to prevent a rainbow table attack.
---

feat: use the first install time as salt and bump pbkdf2 to 100,100

---

src/hooks/useLockApplicationOnBlur.ts
src/hooks/useSaveAccount.ts
src/recoil/accounts.ts
src/screens/SaveGeneratedAccount/useHooks.ts

This PR introduces the new `useHasAccount` hook to know whether ot not the user has one account stored inside the device. By doing this we should limit the re-creation of hooks that previously relied on the entire accounts list. Instead of being re-created each time an account is added or removed, this hook is triggered only when the accounts list has its first item added or its last item removed.  
---

feat: add useHasAccount hook

---

src/hooks/useActiveAccountBalance.ts

This PR fixes the account balance component by displaying a 0 balance instead of nothing when the account does not have any coins.
---

fix: balance not visible for accounts that don't have coins

---

src/hooks/useGetPasswordFromBiometrics.ts
src/lib/AppStateUtils/index.ts

Closes: #XXXX
This PR fixes a bug that cause the missing visualization of the splash screen on Android when the application goes on `blur`. This is caused from the fact that if the application requires the biometrics authentication shortly after the user have unlocked the device the biometrics popup is not showed to the user and so the application don't goes on `blur` state and the `noSplashScreen` flag is not cleared causing the application to not show the splash screen if the user opens another application.
---
your handle next to the items reviewed if you only …

fix: fix splash screen not been visualized on Android after unlocking the device

---

src/hooks/useImportAccount.ts
src/navigation/RootNavigator/index.tsx
src/screens/CheckWalletPassword/index.tsx
src/screens/ImportAccountSelectType/index.tsx
src/screens/Landing/index.tsx

This PR adds the ability to customize the title and description of the screen allowing to import an account, to distinguish between when an account is imported inside the app and when a chain is being linked. 
---

feat: allow to customize import account screen title and description

---

src/assets/locales/en/profile.json
src/screens/Profile/components/ApplicationLinks/index.tsx
src/screens/Profile/components/ChainLinksList/index.tsx
src/screens/Profile/components/ProfileData/index.tsx
src/screens/Profile/index.tsx

This PR improves the loading of the profile screen by using the `LoadingModal` instead of a `StyledActivityIndicator`. All data is now also loaded in the same place (right after opening the profile screen), instead of in two different places (`Profile` and `ProfileData`). This should provide a better UX by allowing the user to visualize the profile data only when all the data are properly loaded. 
---

feat: improve profile loading

---

src/lib/SecureStorage/index.ts

Closes: #XXXX
This PR fixes a bug that prevent the authentication with biometrics if the user changes password after enabling the biometrics login or the sign transactions with biometrics.
---

fix: fix biometrics passwords not updated when changing application password

---

src/hooks/useReturnToCurrentScreen.ts

Closes: #XXXX
This PR fixes the `useReturnToCurrentScreen` hook to execute the `navigate` action only if the screen where will should return exists in the navigator state.
---

fix: fix return to current screen hook

---

src/screens/Home/components/TransactionsList/index.tsx

Closes: #XXXX
This PR fixes the transactions section header not updating correctly.  
Unfortunally the bug is casued from this issue (https://github.com/Shopify/flash-list/issues/615 ) of the `FlashList` library.
---

fix: fixed first transactions section header not updating

---

src/hooks/useImportNewAccount.ts
src/hooks/useReturnToCurrentScreen.ts
src/hooks/useSelectAccount.ts
src/screens/CheckMnemonic/index.tsx
src/screens/ImportAccountFromMnemonic/index.tsx
src/screens/ImportAccountSelectLedgerApp/index.tsx
src/screens/Landing/index.tsx

Closes: #XXXX
This PR fixes a navigation glitch that cause the visualization of the `Landing` screen while importing a new account.
---

fix: fix ui navigation glitch when importing a new account

---

src/components/AvatarImage/useStyles.ts
src/components/StyledSafeAreaView/index.tsx
src/screens/CheckWalletPassword/index.tsx
src/screens/CreateWalletPassword/index.tsx
src/screens/EditProfile/index.tsx
src/screens/ImportAccountFromMnemonic/index.tsx
src/screens/ScanQr/index.tsx
src/screens/SelectAccount/components/AccountPicker/index.tsx
src/screens/SelectAccount/components/AccountPicker/useStyles.ts
src/screens/SelectAccount/components/PaginatedFlatList/index.tsx
src/screens/SelectAccount/index.tsx
src/screens/SendTokens/index.tsx
src/screens/SettingsChangeWalletPassword/index.tsx
src/screens/SettingsEnableBiometricsAuthorization/index.tsx
src/screens/UnlockApplication/index.tsx

- Added a new `TouchableWithoutFeedback` to close the KB when the user click outside the KB. Wherever there is a `TextInput` a new prop called `touchableWithoutFeedbackDisabled={true}` must be passed to the `StyledSafeAreaView`
- Fixed the Avatar loading style and the item separators style
---

fix: added a TouchableWithoutFeedback to close the keyboard on iOS + UI fixes

---

src/screens/CreateWalletPassword/index.tsx

Closes: #XXXX
This PR changes the `CreateWalletPassword` screen adding a second input that let the user confirm the password without navigating to the `CheckWalletPassword` screen.
---

feat: improve app password creation screen

---

src/screens/Landing/index.tsx
src/screens/Landing/useStyles.ts

Closes: #XXXX
This PR updates the UI of the landing page adding a divider around the "Or login with" text.  
Previous Landing:
New Landing:  
---

feat: add a divider around "or login with" label in landing page

---

src/lib/FormatUtils/index.ts
src/screens/ImportAccountFromMnemonic/index.tsx

Closes: #XXXX
This PR fixes the mnemonic sanitization logic in the `ImportAccountFromMnemonic`.  
Before the mnemonic input was sanitizing the text removing the ending spaces and so previnting the user to properly type the menemonic.
---

fix: fix mnemonic sanitization logic

---

src/hooks/walletconnect/useInitWalletConnectClient.ts
src/hooks/walletconnect/useWalletConnectOnSessionExpire.ts

Closes: #XXXX
This PR fixes the a bug that cause the application to not remove the expired WalletConnect sessions.
---

fix: fix WalletConnect expired sessions not being removed

---

src/lib/MMKVStorage/encoding/index.ts
src/lib/MMKVStorage/encoding/serializers/date.ts
src/lib/MMKVStorage/index.test.ts

Closes: #XXXX
This PR fixes the wrong handling of `null` data when serializing the data begin saved inside MMKV.
---

fix: fix null handling in MMKV serialization/deserialization

---

src/assets/locales/config.ts
src/assets/locales/i18n.ts
src/assets/locales/i18next.d.ts

Closes: #XXXX
This PR fixes the linting error related to `i18next` by updating the Typescript type defintions removing the possibility of receiving a `null` value when calling the `t` function to get the localized text.
---

chore: fix linting error related to i18next

---

src/components/Button/useStyles.ts
src/screens/SelectAccount/components/AccountPicker/index.tsx
src/screens/SelectAccount/components/PaginatedFlatList/index.tsx

Closes: #XXXX
This PR improves the loading speed when importing an account with the Ledger device.To achive this I have reduced the amount of accounts generated for each page from 15 to 10.
This PR fixes also a bug that couse a communication error with the Ledger if the user toggle the `HdPath` picker while the app is generating a page of accounts.
---

feat: improve Legder account generation speed

---

src/assets/locales/en/account.json
src/assets/locales/en/settings.json
src/lib/SecureStorage/errors.ts
src/lib/SecureStorage/index.ts
src/screens/SettingsChangeWalletPassword/index.tsx
src/screens/UnlockApplication/index.tsx
src/screens/UnlockWallet/index.tsx

Closes: #XXXX
This PR fixes a bug that prevents the wallet unlock if the user insert a wrong password.
---

fix: allow user to re-insert wrong password during wallet unlock

---

src/assets/locales/en/messages/common.json
src/assets/locales/en/messages/index.ts
src/assets/locales/en/messages/reactions.json
src/components/Messages/components.ts
src/components/Messages/posts/MsgAddPostAttachment/MsgAddPostAttachmentDetails/index.tsx
src/components/Messages/posts/MsgAnswerPoll/MsgAnswerPollDetails/index.tsx
src/components/Messages/posts/MsgDeletePost/MsgDeletePostDetails/index.tsx
src/components/Messages/posts/MsgRemovePostAttachment/MsgRemovePostAttachmentDetails/index.tsx
src/components/Messages/reactions/MsgAddReaction/MsgAddReactionDetails/hooks.ts
src/components/Messages/reactions/MsgAddReaction/MsgAddReactionDetails/index.tsx
src/components/Messages/reactions/MsgAddReaction/MsgAddReactionListItem/index.tsx
src/components/Messages/reactions/MsgAddReaction/index.tsx
src/components/Messages/reactions/MsgAddRegisteredReaction/MsgAddRegisteredReactionDetails/index.tsx
src/components/Messages/reactions/MsgAddRegisteredReaction/MsgAddRegisteredReactionListItem/index.tsx
src/components/Messages/reactions/MsgAddRegisteredReaction/index.tsx
src/components/Messages/reactions/MsgEditRegisteredReaction/MsgEditRegisteredReactionDetails/index.tsx
src/components/Messages/reactions/MsgEditRegisteredReaction/MsgEditRegisteredReactionListItem/index.tsx
src/components/Messages/reactions/MsgEditRegisteredReaction/index.tsx
src/components/Messages/reactions/MsgRemoveReaction/MsgRemoveReactionDetails/index.tsx
src/components/Messages/reactions/MsgRemoveReaction/MsgRemoveReactionListItem/index.tsx
src/components/Messages/reactions/MsgRemoveReaction/index.tsx
src/components/Messages/reactions/MsgRemoveRegisteredReaction/MsgRemoveRegisteredReactionDetails/index.tsx
src/components/Messages/reactions/MsgRemoveRegisteredReaction/MsgRemoveRegisteredReactionListItem/index.tsx
src/components/Messages/reactions/MsgRemoveRegisteredReaction/index.tsx
src/components/Messages/reactions/MsgSetReactionsParams/MsgSetReactionsParamsDetails/index.tsx
src/components/Messages/reactions/MsgSetReactionsParams/MsgSetReactionsParamsListItem/index.tsx
src/components/Messages/reactions/MsgSetReactionsParams/index.tsx
src/components/Messages/subspaces/MsgDeleteSubspace/MsgDeleteSubspaceDetails/index.tsx
src/lib/EncodeObjectUtils/reactions.ts
src/lib/TransactionUtils/decoders.ts

Closes: #XXXX
This PR adds the support to the following `x/reactions` messages:
- MsgAddReaction
- MsgRemoveRegisteredReaction
- MsgAddRegisteredReaction
- MsgSetReactionsParams
- MsgRemoveReaction
- MsgEditRegisteredReaction
---

feat: add support to x/reactions messages

---

android/app/src/main/java/network/desmos/dpm/MainApplication.java
package.json
patches/@noble+hashes+1.1.5.patch
patches/README.md
shim.js
yarn.lock

Closes: #XXXX
This PR removes the v8 engine from the android version in order to decrease the apk size.
The new size of the applications compiled without v8 are:
* `arm64-v8a`: 47MB vs 68.1MB
* `armeabi-v7a`: 38MB vs 54.9MB
---

build(android): removed v8 engine

---

src/components/DesmosPostHogProvider/index.tsx
src/hooks/analytics/useIdentifyForPreviouslyCreatedAccounts.ts
src/hooks/analytics/useIdentifyUser.ts
src/recoil/accounts.ts
src/recoil/analytics.ts
src/types/analytics.ts

Closes: #XXXX
This PR implements the PostHog user identifications, howewer since on DPM we don't have a way to have a id that uniquely identify an user between multiple devices we keep the generated anonymus id provided from PostHog and we save as properties the hash of the addresses of the accounts imported from the user.
---

feat: add PostHog user identification

---

src/hooks/staking/useAccountPendingStakingRewards.ts
src/hooks/staking/useAccountRedelegationsFrom.ts
src/hooks/staking/useTotalDelegatedAmount.ts
src/hooks/staking/useTotalRedelegatingAmount.ts
src/hooks/staking/useTotalUnbondingAmount.ts
src/hooks/staking/useValidatorStakedAmount.ts
src/hooks/staking/useValidatorUnbondingDelegations.ts
src/hooks/useActiveAccountTransactions.ts
src/screens/Home/components/AccountBalances/index.tsx
src/screens/Home/index.tsx

Closes: #XXXX
This PR fixes a bug where the balances are not displayed when returning to the home.
Ti bug was caused from the fact that the server was returning an error related to the query of data in a block that has yet to be produced.
To fix this I leveregd the apollo cache so that the application now gently fallback to the last fetched data, in this case the app will just show a non up to date information instead of nothing, the information can be later updated from the user with the pull to refresh gesture. This also have the benefit of making the UI showing the content loaders since the `loading` flag of apollo will correctly refelect the status of the request unlike before.
This is the final result:
---
*All items are required. Please add a note to the item if the item is not …

fix: balance not displayed when returning to the home

---

patches/react-native-bootsplash+4.4.1.patch

Closes: #XXXX
This PR fixes a crash on Android when the application is closed during the visualization of the splash screen and immediately reopened.
---

fix: fix splash screen loading crash

---

src/assets/locales/en/transaction.json
src/components/DesmosPostHogProvider/index.tsx
src/components/FeatureFlags/index.ts
src/components/TransactionDetails/index.tsx
src/hooks/featureflags/useAppFeatureFlags.ts
src/lib/LedgerUtils/commands.ts
src/lib/PromiseUtils/index.ts
src/lib/PromiseUtils/timeout.test.ts
src/lib/PromiseUtils/timeout.ts
src/lib/Timer/index.ts
src/screens/BroadcastTx/hooks.ts
src/screens/BroadcastTx/index.tsx
src/screens/DevScreen/index.tsx
src/types/appFeatureFlags.ts

Closes: DPM-73, DPM-72
This PR improves the fee estimation procedure by enforcing a timeout that if exceed the application will fallback to a default fee value.
The default fee amount and allowed execution time can be configured with some feature flags from Posthog.
On top of this I have added an analytics to track the amount of time that the application is abble to correctly estimate the fee in the provided time to be able to tune the timeout value. This analytics can be enabled/disbale through a Posthog feature flag.
---
your handle next to the items reviewed if …

feat: improve transaction fee estimation functionality

---

src/screens/ImportAccountFromMnemonic/index.tsx
src/screens/ImportAccountFromMnemonic/useStyles.ts

Closes: DPM-99
This PR fixes a bug that prevent the user to write their mnemonic if the first letter is uppercase.
To solve this since all the words of a mnemonic should be lowercase the input now disable the auto capitalization so that all the text is in lowercase.
---

fix: mnemonic input not allowing the user to write if the first letter is uppercase

---

src/hooks/uriactions/useHandleUriAction.tsx
src/screens/ScanQr/index.tsx
src/screens/SendTokens/index.tsx
src/screens/WalletConnectSessions/components/EmptySessions/index.tsx
src/types/uri.ts

Closes: DPM-151
This pull PR addresses a bug that causes the application to display an "Invalid QR code" message when scanning a valid WalletConnect QR code. Additionally, it enhances the logic for scanning another user's QR code when performing a token send.
---

fix: qr code scanning logic

---

src/assets/locales/en/common.json
src/hooks/apollo/useAutoCancelQuery.ts
src/screens/SelectAccount/components/AccountListItem/index.tsx
src/screens/SelectAccount/components/AccountListItemBalance/index.tsx
src/screens/SelectAccount/components/AccountListItemBalance/useStyles.ts

Closes: DPM-152
This PR introduces the feature to display the account balance when importing a Desmos account.
Here a screen of the final result:
---

feat: add balance visualization when importing a Desmos account

---

src/lib/FormatUtils/index.ts

Closes: DPM-157
This PR addresses a bug where on devices with a locale that doesn't have a thousand separator, numbers are incorrectly formatted and parsed.
---

fix: handle locales without thousands separator

---

src/components/Flexible/Section/index.tsx

Closes: DPM-159
This PR fixes a bug that was causing the display of two dividers between the "Switch chain" and "Analytics" options in the settings screen.
---

fix: multiple dividers in settings sections

---

src/screens/CheckWalletPassword/index.tsx
src/screens/CreateWalletPassword/index.tsx
src/screens/EditProfile/index.tsx
src/screens/ImportAccountFromMnemonic/index.tsx
src/screens/SettingsChangeWalletPassword/index.tsx
src/screens/SettingsEnableBiometricsAuthorization/index.tsx
src/screens/UnlockApplication/index.tsx
src/screens/UnlockWallet/index.tsx

This PR replaces various `KeyboardAvoidingView` usages with the custom `DKeyboardAvoidingView` component that does not require speciying the various params.
---

refactor: replace KeyboardAvoidingView with DKeyboardAvoidingView

---

src/modals/AmountAndMemoModal/index.tsx
src/modals/AmountAndMemoModal/useStyles.ts
src/modals/ModalScreen/index.tsx

Closes: DPM-174
This PR updates what was done with #251 by reverting the changes to the `ModalScreen` component and moving the usage of the `DKeyboardAvoidingView` inside the `AmountAndMemoModal` instead. 
It also improves the bottom padding of `AmountAndMemoModal` by making it non-zero only for iOS devices, to prevent visualization issues with the `DKeyboardAvoidingView`. 
**Note**: A test run on the iOS simulator is needed from @ale-mazz before releasing this. The things that should be tested are:
1. The `AmountAndMemoModal` is shown properly, and trying to input something does not make the keyboard cover everything (BON-173).
2. The `SingleButtonModal` is shown properly, and the paddings on the content are set properly (BON-174).
---
*All items are required. Please add a note to the …

refactor: update modal behavior

---

src/lib/FormatUtils/index.ts
src/screens/GovernanceProposalDetails/components/ProposalDetails/index.tsx

Closes: DPM-164
This PR fixes a bug that prevents the display of inline code when converting markdown text into plain text.
---

fix: inline code not displayed when converting markdown text to plaintext

---

src/assets/locales/en/settings.json
src/components/Flexible/SectionSwitch/index.tsx
src/hooks/useLockApplicationOnBlur.ts
src/modals/TwoButtonModal/index.tsx
src/navigation/RootNavigator/index.tsx
src/navigation/routes.ts
src/recoil/settings.ts
src/screens/Settings/hooks.ts
src/screens/Settings/index.tsx
src/screens/SettingsSwitchScreen/index.tsx
src/screens/SettingsSwitchScreen/useStyles.ts
src/types/settings.ts

Closes: DPM-160
This PR introduces a setting in the Security section that enables the user to disable the password prompt for unlocking the application when it is started and when it is resumed from the background.
Here the final result:
---

feat: allow to disable the password prompt at application open and resume

---

src/screens/BroadcastTx/hooks.ts

Closes: DPM-177
This PR addresses a bug that causes certain transactions to fail with the "out of gas" error.
---

fix: gas adjustment

---

src/hooks/useUnlockWallet.ts
src/lib/WalletUtils/generate.ts
src/recoil/wallet.ts
src/screens/UnlockWallet/useHooks.ts
src/types/wallet.ts

Closes: DPM-165
This PR enables the application to keep the user's wallets unlocked after they have been initially unlocked. This helps to speed up operations and prevent multiple password prompts.
---

feat: keep wallet unlocked after first unlock

---

src/hooks/usePaginatedData.ts
src/screens/ScanQr/components/QrCodeScanner/index.tsx
src/screens/SelectAccount/components/AccountPicker/useHooks.ts
src/screens/SelectValidator/index.tsx
src/screens/SendTokens/components/RecipientsList/hooks.ts

Closes: DPM-184
This PR updates the `usePaginatedData` hook with changes made while working on other projects.  
The new features include:
1. The possibility to implement caching logic using the `onDataChanged` field.
2. The ability to execute an operation before data is refreshed through the `preRefetchAction` field.
3. The option to get the total item count through the `getTotalItemsCount` field.
Additionally, the changes improve some behaviors of the hook:
1. Fix weird refresh behaviors on iOS.
2. Avoid performing a fetch request when all elements have been fetched.
---
*All items are required. Please add a note if the item is not applicable and …

feat: update usePaginatedData hook

---

src/components/TextInput/useStyles.ts
src/screens/ImportAccountFromMnemonic/index.tsx
src/screens/ImportAccountFromMnemonic/useStyles.ts
src/screens/Stake/index.tsx
src/screens/Stake/useStyles.ts

Closes: DPM-185
This PR addresses a bug in iOS that was causing the send input to display the user's address in multiple lines instead of a single one.
---

fix(ios): send input visualization after pasting and address on iOS
