desmos-labs/dpm

.github/mergify.yml
.github/pull_request_template.md

Added a new _PR template_ and a _mergify_ workflow

chore: CI improvements 

---

src/components/FlexibleSection/SectionButton.tsx
src/screens/Settings.tsx

Closes: #75 
---
please add links to any relevant follow-up issues.*

fix: disable chain switching

---

package.json

chore: release v1.0.8

---

src/hooks/useInitAppState.ts
src/navigation/RootStackScreens.tsx
src/sources/AccountSource.ts
src/sources/LocalWalletsSource.ts
src/sources/ProfileSource.ts

fix: global password flow

---

src/components/ProfileHeader/useHooks.ts
src/hooks/useDelletPasswordFromBiometrics.ts
src/hooks/useGetPasswordFromBiometrics.ts
src/hooks/useLockApplicationOnBlur.ts
src/hooks/usePermissions.ts
src/navigation/RootNavigator/index.tsx
src/recoil/appState.ts
src/screens/PerformLedgerScan/useHooks.ts
src/screens/SplashScreen/index.tsx
src/types/appState.ts
yarn.lock

Closes: #XXXX
This PR adds the visualization of the `SplashScreen` when the aplication goes on `blur` state on Android to hide the application content.   
The `blur` state is triggered when the user opens the recent app list or when opens another application.
---

feat: splash screen on aplication blur on android

---

src/screens/DevScreen/index.tsx

This PR imrpoves the DevScreen by removing now useless buttons and information
---

chore: clean DevScreen

---

src/lib/AccountUtils/deserialize.ts
src/lib/AccountUtils/serialize.ts

This PR is just a small fix to the formatting of the accounts (de)serialization method to remove useless blank lines and group togehter lines that represent a unique logic unit.
---

chore: improved accounts (de)serialization formatting

---

android/app/build.gradle
src/screens/SelectAccount/components/AccountPicker/index.tsx
src/screens/SelectAccount/components/HdPathPicker/index.tsx
src/screens/SelectAccount/index.tsx

This PR improves the address generation screen by moving the debounce inside each HD path value input. It also improves how the UI reacts to the generation of the addresses by making it impossible to interact with any input while a new address is being generated.
---

feat: improve address generation debounce

---

src/hooks/useSaveAccount.ts

Closes: #XXXX
This PR fix a bug that prevent the user to create the password to protect the accounts private keys
---

fix: first account save not allowing to create password 

---

ios/DesmosProfileManager.xcodeproj/project.pbxproj
ios/Podfile.lock
src/hooks/useLockApplicationOnBlur.ts

fix: ios unlock loop with inactive state

---

src/components/BlockchainListItem/index.tsx
src/components/DPMImage/index.tsx
src/components/Flexible/SectionButton/index.tsx
src/components/Messages/BaseMessage/BaseMessageDetails/index.tsx
src/components/Messages/BaseMessage/BaseMessageListItem/index.tsx
src/components/Messages/MsgLinkChainAccount/MsgLinkChainAccountDetails/index.tsx
src/components/Messages/MsgUnlinkChainAccount/MsgUnlinkChainAccountDetails/index.tsx
src/lib/ImageUtils/index.ts
src/screens/ChainLinkDetails/index.tsx
src/screens/Home/components/AppDrawer/index.tsx
src/screens/Landing/index.tsx
src/screens/Profile/components/ApplicationLinkItem/index.tsx
src/screens/Profile/components/ChainLinkItem/index.tsx
src/screens/SplashScreen/index.tsx
src/screens/WalletConnectSessionProposal/index.tsx

This PR replaces all the `Image` usages with `FastImage` in order to enabling caching and improving performances.
---

feat: replace Image with FastImage

---

src/components/AvatarImage/index.tsx
src/components/AvatarImage/props.ts
src/components/AvatarImage/useStyles.ts
src/components/ProfileImage/index.tsx
src/screens/SelectAccount/components/AccountListItem/index.tsx
src/screens/SelectAccount/components/AccountListItem/useHooks.ts
src/screens/SelectAccount/components/AccountPicker/index.tsx
src/screens/SelectAccount/components/AccountPicker/useStyles.ts
src/screens/SelectAccount/components/PaginatedFlatList/index.tsx

Closes: #XXXX
This PR improves the performance of the `AccountPicker` component reducing the drop of the `JS` thread FPS.
---

feat: improve account picker performance

---

package.json
shim.js
yarn.lock

Closes: #XXXX
This PR polyfill `Intl.PluralRules` to support the new i18n plurals syntax.
---

feat: polyfill Intl PluralRules

---

src/App.tsx
src/components/CopyButton/index.tsx
src/lib/SnackBarProvider/index.tsx
src/lib/SnackBarProvider/recoil.ts
src/lib/SnackBarProvider/types.ts
src/lib/SnackBarProvider/useStyles.ts

Closes: #XXXX
This PR adds a global `SnackBarProvider` that handle the visualization of a snackbar in the applicaton.  
The snackbar can be presented to the user using the `useShowSnackBar` hook.
---

feat: custom app snackbar

---

src/screens/SendTokens/index.tsx

Fixed transaction description inside the `SendTokens` screen.
---

fix: fixed tx description inside SendTokens

---

package.json
src/assets/locales/en/account.json
src/screens/ImportAccountSelectChain/useStyles.ts
src/screens/ImportAccountSelectType/components/ImageButton/index.tsx
src/screens/ImportAccountSelectType/components/ImageButton/useStyles.ts
src/screens/ImportAccountSelectType/index.tsx
src/screens/ImportAccountSelectType/useStyles.ts
src/screens/Landing/index.tsx
yarn.lock

Closes: #XXXX
This PR fixes the image inside the `ImageButton` component not being displayed.
---

fix: fix import account buttons

---

src/assets/locales/en/settings.json
src/components/TopBar/useStyles.ts
src/screens/CheckMnemonic/index.tsx
src/screens/CreateNewMnemonic/index.tsx
src/screens/ImportAccountFromMnemonic/index.tsx
src/screens/Legal/index.tsx
src/screens/SelectAccount/index.tsx
src/screens/SettingsEnableBiometricsAuthorization/index.tsx

Closes: #XXXX
This PR remove the `Typography.Title` components from all the screens in favor of the `TopBar` title attribute.
---

feat: use TopBar title in all the screens

---

.github/workflows/release-android.yaml
.github/workflows/release-ios.yaml
fastlane/Fastfile

Closes: #XXXX
This PR adds a step to the release jobs to generate the `.env` file.  
The file `.env` will be populated with all the environment variables that starts with `ENV_`.
---

ci: add step to write .env file containing the app config

---

src/components/ContentLoaders/ChainLink/index.tsx
src/components/ContentLoaders/Typography/index.tsx
src/components/ProfileHeader/index.tsx
src/components/ProfileHeader/useStyles.ts
src/components/ThemedContentLoader/index.tsx
src/config/theme/DarkTheme.ts
src/config/theme/LightTheme.ts
src/config/theme/customTheme.d.ts
src/screens/EditProfile/index.tsx
src/screens/Profile/components/ApplicationLinks/index.tsx
src/screens/Profile/components/ProfileData/index.tsx

Closes: #XXXX
This PR adds a custom `ThemedContentLoader` that follows the system theme.
---

feat: themed activity indicator that follows the system theme

---

src/hooks/useSignTx.ts

Closes: #XXXX
This PR fixes the translation of the popup that is shown to the user when signing a transaction with the Ledger.
---

fix: fix wait for ledger confirm translation

---

src/screens/SettingsSwitchChain/index.tsx

feat: memoize objects in SettingsSwitchChain screen

---

src/hooks/profile/useUpdateAccountsProfile.ts
src/hooks/profile/useUpdateAccountsProfiles.ts
src/navigation/RootNavigator/index.tsx
src/recoil/profiles.ts

Closes: #XXXX
This PR add the logic to update the user's profiles when thes user changes chain.
---

feat: update the profile associated to the user accounts on chain change

---

android/app/src/main/assets/custom/privacy.md
android/app/src/main/assets/custom/tos.md
android/link-assets-manifest.json
assets/md/privacy.md
assets/md/tos.md
ios/DesmosProfileManager.xcodeproj/project.pbxproj
ios/DesmosProfileManager/Info.plist
ios/link-assets-manifest.json
package.json
src/screens/Settings/index.tsx

Closes: #153
Closes: #61 
This PR adds a Teram Of Service sections in the Settings screen and update the privacy policy document.
---

feat: add tos and update privacy policy 

---

src/assets/locales/en/landing.json
src/hooks/legal/useShowPrivacyPolicy.ts
src/hooks/legal/useShowToS.ts
src/screens/Landing/index.tsx
src/screens/Landing/useStyles.ts
src/screens/Settings/index.tsx

Closes: #XXXX
This PR adds a legal disclamer in the `Landing` screen where the user can click on the bold text to see the terms of service and the privacy policy.
Here a preview of the result:
---

feat: add legal disclamer in the Landing screen

---

package.json
src/assets/locales/en/index.ts
src/assets/locales/en/messages/feegrant.json
src/assets/locales/en/messages/index.ts
src/assets/locales/i18next.d.ts
src/components/Messages/MsgGrantAllowance/MsgGrantAllowanceDetails/index.tsx
src/components/Messages/MsgGrantAllowance/MsgGrantAllowanceListItem/index.tsx
src/components/Messages/MsgGrantAllowance/index.ts
src/components/Messages/MsgRevokeAllowance/MsgRevokeAllowanceDetails/index.tsx
src/components/Messages/MsgRevokeAllowance/MsgRevokeAllowanceListItem/index.tsx
src/components/Messages/MsgRevokeAllowance/index.ts
src/components/Messages/MsgUnknown/MsgUnknownDetails/index.tsx
src/components/Messages/components.ts
src/lib/FeegrantUtils/parse.ts
yarn.lock

Closes: #51 
This PR add support to the following message types:
- `MsgGrantAllowance`
- `MsgRevokeAllowance`
---

feat: add support to x/feegrant messages

---

src/assets/locales/en/messages/authz.json
src/assets/locales/en/messages/index.ts
src/components/Messages/BaseMessage/BaseMessageDetails/index.tsx
src/components/Messages/MsgGrant/MsgGrantDetails/hooks.ts
src/components/Messages/MsgGrant/MsgGrantDetails/index.tsx
src/components/Messages/MsgGrant/MsgGrantListItem/index.tsx
src/components/Messages/MsgGrant/index.ts
src/components/Messages/MsgRevoke/MsgRevokeDetails/index.tsx
src/components/Messages/MsgRevoke/MsgRevokeListItem/index.tsx
src/components/Messages/MsgRevoke/index.ts
src/components/Messages/components.ts
src/lib/TransactionUtils/decoders.ts
src/types/cosmos-staking.ts

Closes: #XXXX
This PR adds support to the following x/authz messages:
- MsgGrant
- MsgRevoke
---

feat: add partial support to x/authz messages

---

src/config/LinkableChains.ts

Closes: #XXXX
This PR updates the Likecoin address prefix used to generate the address when performing a chain link
---

feat: update LikeCoin address prefix

---

.github/workflows/static-analysis.yaml
.gitignore
sonar-project.properties
src/screens/CheckMnemonic/index.tsx

This PR sets up the SonarQube static analyses to be run on the `src` folder everytime we push to a PR or the `main` branch.
Relates to [DCDC-261](https://forbole.atlassian.net/browse/DCD-261)
---

build(ci): add SonarQube static analysis GitHub workflow

---

Gemfile
ios/DesmosProfileManager.xcodeproj/project.pbxproj
ios/Podfile.lock
package.json
yarn.lock

fix: xcode critical bug

---

SUPPORT.md

Closes: #XXXX
This PR adds a `SUPPORT.md` file that contains the support contacts that can be used to report bugs and provide feedbacks.
---

docs: add a SUPPORT.md file

---

package.json
src/assets/locales/en/web3auth.json
src/hooks/useShowModal.ts
src/modals/ModalScreen/index.tsx
src/modals/ModalScreen/useStyles.ts
src/modals/Web3AuthLoginProvidersModal/components/LoginProviderListItem/index.tsx
src/modals/Web3AuthLoginProvidersModal/components/LoginProviderListItem/useStyles.ts
src/modals/Web3AuthLoginProvidersModal/index.tsx
src/modals/Web3AuthLoginProvidersModal/useStyles.ts
src/screens/DevScreen/index.tsx
src/screens/DevScreen/useStyles.ts
src/screens/Landing/index.tsx
src/screens/Landing/useStyles.ts
yarn.lock

Closes: #XXXX
This PR updates the style of the popup that shows the other Web3Auth login provider to be aligned with the new landing page desing.
Here the final result:
---

feat: update landing page desing

---

src/assets/locales/en/index.ts
src/assets/locales/en/ledger.json
src/screens/ConnectToLedger/hooks.ts
src/screens/ConnectToLedger/index.tsx
src/screens/PerformLedgerScan/index.tsx

Closes: #XXXX
This PR improves the connection status visualization when the user is connecting to a Ledger device providing more informations on what the application is doing during the connection procedure.
---

feat: improve Ledger connection status visualization

---

src/assets/locales/en/common.json
src/lib/SecureStorage/index.ts
src/screens/CheckWalletPassword/index.tsx
src/screens/UnlockApplication/index.tsx
src/screens/UnlockWallet/index.tsx

Closes: #XXXX
This PR fixes a bug in the biometric unlock logic that cause the application to be stuck in the unlocking procedure if the user cancel the biometric prompt. 
---

fix: biometrics unlock prompt

---

src/components/DesmosPostHogProvider/index.tsx
src/hooks/analytics/useTrackAppOpened.ts
src/screens/Settings/index.tsx

Closes: [DPM-86](https://desmoslabs.atlassian.net/browse/DPM-86)
---
[DPM-86]: https://desmoslabs.atlassian.net/browse/DPM-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: track Application Opened event

---

android/app/src/main/assets/custom/privacy.md
android/link-assets-manifest.json
ios/DesmosProfileManager.xcodeproj/project.pbxproj
ios/link-assets-manifest.json

Closes: #XXXX
This PR links the new privacy policy file so that the application will show the new file
---

chore: linked the new privacy policy file

---

android/app/src/main/assets/custom/tos.md
android/link-assets-manifest.json
assets/md/tos.md
ios/DesmosProfileManager.xcodeproj/project.pbxproj
ios/link-assets-manifest.json

Closes: DPM-92
This PR updates the in-app terms of service
---

feat: update ToS file

---

src/components/DesmosPostHogProvider/index.tsx

Closes: DPM-96
This PR changes the posthog configurations to use the european server
---

feat: use european server for posthog

---

src/screens/ManageStaking/index.tsx

Closes: #XXXX
This PR adds a button in the Top bar of the `ManageStaking` screen that allow the user to delegate to a validator 
---

feat: add a stake button in the top bar of ManageStaking screen

---

src/hooks/useOnScreenDetached.ts
src/recoil/home.ts
src/screens/BroadcastTx/index.tsx
src/screens/Home/components/TransactionsListItem/index.tsx
src/screens/Home/hooks.ts
src/screens/Home/index.tsx
src/screens/SettingsSwitchChain/index.tsx

Closes: #XXXX
This PR improves the home refresh logic using a global flag that tells if the home should reload the data.
This is a temporary workaround untill we have a proper application wide cache.
---

feat: improve home refresh logic

---

src/assets/locales/en/common.json
src/screens/ManageStaking/tabs/Staked/hooks.ts

Closes: DPM-105
This PR updates the delegations list to filter out the delegations that have amount equal to 0.
---

fix: filter delegations with amount equal to 0

---

package.json
src/assets/locales/en/governance.json
src/components/Badge/index.tsx
src/components/Badge/props.ts
src/components/Badge/useStyles.ts
src/components/ProposalStatusBadge/index.tsx
src/components/Typography/config.ts
src/components/Typography/index.tsx
src/config/theme/LightTheme.ts
src/config/theme/customTheme.d.ts
src/lib/FormatUtils/index.test.ts
src/lib/FormatUtils/index.ts
src/screens/GovernanceProposals/components/ProposalListItem/index.tsx
src/screens/GovernanceProposals/components/ProposalListItem/useStyles.ts
src/screens/GovernanceProposals/hooks.ts
src/screens/GovernanceProposals/index.tsx
src/services/graphql/queries/GetProposals.ts
src/services/graphql/queries/fragments/ProposalFields.ts
src/types/proposals.ts
yarn.lock

Closes: DPM-79
This PR implements the visualization of the proposals.
Here the final result:
---

feat: add proposal list screen

---

src/hooks/messages/useGetMessageAmount.ts
src/screens/Home/components/TransactionsListItem/index.tsx

feat: remove amount from transactions list items where not necessary

---

src/screens/Home/index.tsx

feat: hide vertical scroll indicator in the home screen

---

src/components/RadioGroup/index.tsx

feat: made the entire element of a RadioGroup clickable

---

ios/DesmosProfileManager.xcodeproj/project.pbxproj
ios/Podfile.lock
src/components/DpmTabBar/index.tsx
src/components/DpmTabBar/useStyles.ts
src/components/StyledRefreshControl/index.tsx
src/config/theme/LightTheme.ts
src/config/theme/customTheme.d.ts
src/navigation/RootNavigator/HomeTabs/components/BottomBar/useStyles.ts
src/screens/GovernanceProposalDetails/components/Votes/index.tsx
src/screens/GovernanceProposals/index.tsx
src/screens/Home/components/AccountBalancesAction/useStyles.ts
src/screens/Home/index.tsx
src/screens/Home/useStyles.ts
src/screens/ImportAccountSelectType/components/ImageButton/useStyles.ts
src/screens/ManageStaking/index.tsx
src/screens/ManageStaking/tabs/Restaking/index.tsx
src/screens/ManageStaking/tabs/Staked/index.tsx
src/screens/ManageStaking/tabs/Unbonding/index.tsx
src/screens/PerformLedgerScan/components/LedgerDeviceList/index.tsx
src/screens/PerformLedgerScan/components/LedgerDeviceList/useStyles.ts
src/screens/Profile/index.tsx
src/screens/SelectAccount/components/PaginatedFlatList/index.tsx
src/screens/SelectValidator/index.tsx
src/screens/WalletConnectSessions/components/SessionListItem/useStyles.ts
src/screens/WalletConnectSessions/components/SessionsList/index.tsx
src/screens/WalletConnectSessions/components/SessionsList/useStyles.ts

fix: components shadows on iOS

---

src/hooks/staking/useAccountPendingStakingRewards.ts
src/hooks/staking/useTotalDelegatedAmount.ts
src/hooks/staking/useTotalRedelegatingAmount.ts
src/hooks/staking/useTotalUnbondingAmount.ts

fix: application crash when deleting the last account

---

src/assets/locales/en/settings.json
src/modals/ModalScreen/useStyles.ts
src/screens/Settings/hooks.ts
src/screens/Settings/index.tsx

feat: add modal that explain what data the application collects

---

CHANGELOG.md
package.json

chore: release v2.3.0

---

src/hooks/useLoginWithWeb3Auth.ts

Closes: DPM-127
This pull request (PR) addresses a bug that caused the application to navigate back to the landing page when the user opened another application during the web3auth account import flow.
---

fix: reset to landing page during import with Web3Auth

---

src/App.tsx
src/assets/locales/en/common.json
src/assets/locales/en/dataIntegrity.json
src/assets/locales/en/index.ts
src/hooks/dataintegrity/useCheckKeyChainIntegrity.ts
src/hooks/navigation/useResetToScreen.ts
src/lib/SecureStorage/index.ts
src/modals/CorruptedKeychainModal/hooks.ts
src/modals/CorruptedKeychainModal/index.tsx
src/modals/CorruptedKeychainModal/useStyles.ts
src/modals/ModalScreen/index.tsx
src/modals/SingleButtonModal/index.tsx
src/recoil/accounts.ts
src/recoil/applicationLinks.ts
src/recoil/chainLinks.ts
src/recoil/profiles.ts
src/screens/DevScreen/index.tsx

This PR adds a pop-up message to inform the user that the device's keychain is corrupted. The pop-up will prompt the user to clear the corrupted keychain data in order to continue using the app.
Here a preview:
---

feat: handle corrupted keychain

---

src/assets/locales/en/sendTokens.json
src/components/ProfileListItem/index.tsx
src/components/ProfileListItem/useStyles.ts
src/components/StyledSafeAreaView/index.tsx
src/components/TextInput/index.tsx
src/components/TextInput/useStyles.ts
src/screens/SendTokens/components/RecipientsList/hooks.ts
src/screens/SendTokens/components/RecipientsList/index.tsx
src/screens/SendTokens/components/RecipientsList/useStyles.ts
src/screens/SendTokens/index.tsx
src/services/graphql/queries/GetProfilesFromNickNameOrDtag.ts
src/services/graphql/queries/GetProfilesFromNickNameOrDtagOrAddress.ts

Closes: DPM-59
This PR implements the possibility to search for a token send recipiant by their DTag or nickname.
Here a preview of the final result.
---

feat: allow to search a recipient of a token send by their dtag or nickname

---

src/assets/locales/en/dataIntegrity.json
src/modals/CorruptedKeychainModal/index.tsx

feat: update CorruptedKeychainModal text

---

ios/DesmosProfileManager.xcodeproj/project.pbxproj
ios/Podfile.lock
src/hooks/dataintegrity/useCheckKeyChainIntegrity.ts
src/lib/SecureStorage/index.ts
src/screens/UnlockApplication/index.tsx

fix: corrupted data popup visualization on iOS

---

package.json
src/assets/locales/en/common.json
src/hooks/uriactions/useHandleUriAction.tsx
src/lib/UriActions/generate.ts
src/lib/UriActions/index.ts
src/modals/QRCodeAddressModal/hooks.ts
src/modals/QRCodeAddressModal/index.tsx
src/modals/QRCodeAddressModal/useStyles.ts
src/screens/ScanQr/index.tsx
src/services/axios/index.ts
yarn.lock

Closes: DPM-147
Depends-On: #236 
This PR modifies the QR code generation logic to utilize our API for generating the URL, which is then transformed into a QR code.
---

feat: use api to generate the user's qr code

---

src/navigation/RootNavigator/HomeTabs/index.tsx
src/navigation/RootNavigator/HomeTabs/props.ts
src/navigation/RootNavigator/index.tsx
src/navigation/routes.ts
src/screens/WalletConnectSessions/index.tsx

fix: navigation to scan qr code from authorizations screen

---

src/components/DPMImage/index.tsx
src/screens/PerformLedgerScan/components/LedgerDeviceList/useStyles.ts

fix: ledger icon color when in dark mode

---

src/components/StyledMarkdown/index.tsx
src/components/StyledMarkdown/useStyles.ts
src/screens/ValidatorDetails/index.tsx

Closes: DPM-154
This PR corrects the text color of the validator description when the application is in dark mode. It also enhances the component responsible for rendering markdown by applying additional styles for various markdown tags.
---

fix: validator description text color

---

src/components/ProfileHeader/index.tsx
src/components/ProfileHeader/useHooks.ts
src/components/StyledMarkdown/index.tsx
src/components/ValidatorNameWithStatus/index.tsx
src/components/ValidatorNameWithStatus/useStyles.ts
src/components/ValidatorStatus/index.tsx
src/components/ValidatorStatus/useStyles.ts
src/screens/ValidatorDetails/components/ValidatorInfoField/index.tsx
src/screens/ValidatorDetails/index.tsx
src/screens/ValidatorDetails/useStyles.ts

Closes: DPM-155
This pull request (PR) enhances the validator details screen by incorporating the display of the validator profile's cover picture. Additionally, it improves the overall appearance of the biography by supporting certain HTML tags within the markdown view.
Here a screen of the final result:
---

feat: improved validator details screen

---

src/hooks/featureflags/useAppFeatureFlags.ts
src/hooks/featureflags/useFetchAppFeatureFlags.ts
src/lib/FeatureFlagsUtils/index.ts
src/lib/NeverThrowUtils/index.ts
src/recoil/featureFlags.ts
src/screens/Landing/hooks.ts
src/screens/Landing/index.tsx
src/types/appFeatureFlags.ts

This PR introduces the usage of a new `hideSocialLoginsOnVersion` feature flag that allows to hide social login options (Google, Apple, Twitter, etc) from the application.
---

feat: allow to hide social login options with feature flag
